### GET all users
GET http://localhost:8080/api/users

### GET User by ID
GET http://localhost:8080/api/users/2

### GET User by Email
GET http://localhost:8080/api/users/email/jack@example.com

### Create User
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Jack",
  "email": "jack@example.com",
  "password": "jackisthepassword"
}
